name: Build and Access

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.THE_PROJECT }}
  PROJECT_ZONE: europe-west1-b   

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3


    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
       credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
      
    - name: 'Get Project Info'
      run: 'gcloud projects list'
      
   #- name: 'Create secret'
   #  run: 'echo "secret123" > /tmp/file_secret'
    
   #- name: 'Create secret'
   #  run: 'gcloud secrets create my-secret456 --data-file=/tmp/file_secret '
      
    - name: 'List secrets'
      run: 'gcloud secrets list'
  # Array
    - name: 'Array'
      id: arr
      run: |
        arr=()
        for i in "$(gcloud secrets list)"
        do
          if [[ $i == *"secret"* ]]; then
            echo "Yes"
          fi
        done
      
      
      
      
      
      
      
      
      
      
      
      
